name: Pull Latest Changes onto Server

on:
  push:
    tags: 
      - '*'

jobs:
  pull-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set env
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: echo env variable
        run: echo $RELEASE_VERSION

      - name: echo in ssh server for tag version
        uses: appleboy/ssh-action@master
        env:
          TAG_VERSION: $RELEASE_VERSION
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            echo $TAG_VERSION

      # - name: ssh to server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY }}
      #     port: ${{ secrets.PORT }}
      #     script: |
      #       echo hello
      #       cd /var/www/html/todo_list
          # sudo -S -u www-data /bin/bash -c 'git fetch --tags'
          # sudo -S -u www-data /bin/bash -c 'git checkout tags/$(git describe --tags $(git rev-list --tags --max-count=1))'
          # sudo -S -u www-data /bin/bash -c 'git describe'