name: Pull Latest Changes onto Dev Server

on:
  push:
    tags: 
      - 'dev-*'

jobs:
  pull-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ssh to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USERNAME_DEV }}
          key: ${{ secrets.KEY_DEV }}
          port: ${{ secrets.PORT_DEV }}
          script: |
            echo hello
            cd /var/www/html/todo_list
            sudo -S -u www-data /bin/bash -c 'git fetch --tags'
            sudo -S -u www-data /bin/bash -c 'git checkout tags/$(git describe --tags $(git rev-list --tags --max-count=1))'
            sudo -S -u www-data /bin/bash -c 'git describe'