name: Pull Latest Changes onto Dev Server

on:
  push:
    tags: 
      - 'dev-*'

jobs:
  pull-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ssh to server
        uses: appleboy/ssh-action@master
        env:
          RELEASE_VERSION: ${{ github.ref }}
        with:
          envs: RELEASE_VERSION
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo hello
            echo $RELEASE_VERSION
          # cd /var/www/html/todo_list
          # sudo -S -u www-data /bin/bash -c 'git fetch --tags'
          # sudo -S -u www-data /bin/bash -c 'git checkout tags/$(git describe --tags $(git rev-list --tags --max-count=1))'
          # sudo -S -u www-data /bin/bash -c 'git describe'